sonar.projectKey=cohort-9-mern-16436-zuha
sonar.projectName=NoteSpace
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/tests/**

sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info